### ISSUE TITLE
PHash algorithm is wrong

### ISSUE THREAD

**Issue by grooveek** [dozedoff/commonj#9]
You've done a nice refactoring work over Elliot Shepherd initial implementation of PHash.
As I tried to understand the code, I noticed a big mistake in it, in the step 6, which has been reflected in your two methods convertToBitString and convertToLong

https://github.com/dozedoff/commonj/blob/master/src/main/java/com/github/dozedoff/commonj/hash/ImagePHash.java:155

      for (int x = 0; x < smallerSize; x++) {  
			for (int y = 0; y < smallerSize; y++) {
				if (x != 0 && y != 0) {  // <====== No need to skip the first row and column
					hash += (dctVals[x][y] > avg ? "1" : "0");
				}
			}
		}

This code skips entirely 15 bits of valuable information about the image

After a few research, I've noticed this comment in the original article
http://www.hackerfactor.com/blog/index.php?/archives/432-Looks-Like-It.html#c1498
which seems to be the root message of Elliott Shepherd posting his code. The answers spot the same bug I am talking about

**Comment by dozedoff** [comment]
Fix causes CI builds to fail, oraclejdk passes but openjdk fails with wrong hash values.
